#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "오딘 3.0 — data_pipeline API 키 설정"

# 붙여넣기 안전장치: 일부 터미널은 붙여넣기를 이스케이프(bracketed paste: ESC[200~ … ESC[201~)로 감싸
# 키 값에 제어문자를 섞어 넣는다(→ API 호출 시 'Invalid URL' 등으로 깨짐). 아래로 방지·정리한다.
printf '\033[?2004l' 2>/dev/null || true   # 가능하면 붙여넣기 이스케이프 자체를 끔
_sanitize() { printf '%s' "$1" | tr -d '\033\r' | sed -E 's/\[20[01]~//g'; }

note "여기서 입력한 키는 이 컴퓨터의 .env 파일에만 저장됩니다(브레인 §7-2)."
note "화면 입력은 가려지고, 채팅창·로그·공개 레포 어디에도 올라가지 않습니다."
note ".env 는 이미 .gitignore로 커밋이 막혀 있습니다."
pause "계속하려면 Enter"

# ── Stage 1: DART 인증키 ───────────────────────────────────────────────────
stage "DART — 전자공시 OpenAPI 인증키"
say "회사정보·재무·공시·기업코드(corpCode.xml) 호출에 쓰는 열쇠입니다."
open_url "https://opendart.fss.or.kr/"
step "우측 상단에서 회원가입/로그인 (무료)."
step "상단 메뉴 '인증키 신청/관리' → '오픈API 인증키 신청'."
step "가입한 이메일로 40자리 인증키가 도착합니다. 그 값을 복사하세요."
note "이미 발급받은 키가 있으면 '인증키 신청/관리'에서 다시 확인할 수 있습니다."
ask_secret DART_API_KEY "DART 인증키를 붙여넣으세요(입력은 가려집니다):"
DART_API_KEY=$(_sanitize "$DART_API_KEY")
write_env DART_API_KEY "$DART_API_KEY"

# ── Stage 2: KRX 종목정보 키 (공공데이터포털) ──────────────────────────────
stage "KRX 종목정보 — 공공데이터포털(data.go.kr) 서비스키"
say "종목 마스터(dim_stock)를 채우는 열쇠. 공공데이터포털의 '금융위' API를 씁니다."
say "무료이고, 서비스키 1개로 신청한 여러 API를 모두 호출할 수 있습니다."
open_url "https://www.data.go.kr/"
step "회원가입/로그인(무료)."
step "검색창에 '금융위원회 KRX상장종목정보' → 결과에서 '활용신청'."
step "다시 '금융위원회 주식시세정보' 검색 → '활용신청' (시가총액·상장주식수용)."
step "마이페이지 > 데이터활용 > 인증키에서 '일반 인증키'를 복사."
warn "활용신청 승인은 보통 즉시지만 일부는 시간이 걸릴 수 있습니다. 없으면 Enter로 건너뛰고 나중에 재실행."
note "'Decoding' 인증키를 쓰면 편합니다(인코딩키는 이중인코딩 문제가 날 수 있음)."
ask_secret DATA_GO_KR_KEY "공공데이터포털 서비스키를 붙여넣으세요(없으면 Enter):"
DATA_GO_KR_KEY=$(_sanitize "$DATA_GO_KR_KEY")
if [[ -n "${DATA_GO_KR_KEY:-}" ]]; then
  write_env DATA_GO_KR_KEY "$DATA_GO_KR_KEY"
else
  SKIPPED+=("DATA_GO_KR_KEY(종목 마스터) — 나중에 이 wizard 재실행으로 채우기")
  warn "공공데이터포털 키는 건너뜀 — 나중에 다시 실행하세요."
fi

# ── Stage 3: KRX 시장통계 키 (KRX Data Marketplace) ────────────────────────
stage "KRX 시장통계 — KRX Data Marketplace(openapi.krx.co.kr)"
say "시장 통계·일별 매매정보(state_module·분석용)를 채우는 열쇠입니다."
say "위 종목마스터(data.go.kr)와는 다른 포털·다른 키입니다."
open_url "https://openapi.krx.co.kr/"
step "회원가입/로그인 후 'API 이용신청' → 필요한 서비스(예: 일별매매정보)를 신청."
step "마이페이지 'API 인증키 신청'에서 인증키를 발급·복사."
warn "지금 급하지 않으면 Enter로 건너뛰어도 됩니다(state_module 만들 때 있어도 됨)."
ask_secret KRX_API_KEY "KRX Marketplace 인증키를 붙여넣으세요(없으면 Enter):"
KRX_API_KEY=$(_sanitize "$KRX_API_KEY")
if [[ -n "${KRX_API_KEY:-}" ]]; then
  write_env KRX_API_KEY "$KRX_API_KEY"
else
  SKIPPED+=("KRX_API_KEY(시장통계) — state_module 단계에서 채워도 됨")
  warn "KRX 통계 키는 건너뜀 — 나중에 다시 실행하세요."
fi

# ── Stage 4: Supabase 접속정보(새 3.0 DB) ──────────────────────────────────
stage "Supabase — 새 3.0 DB 접속정보(쓰기용)"
say "data_pipeline이 표에 데이터를 쓸 때 필요한 주소와 비밀 키입니다."
say "Project URL 은 보통 이미 .env에 있으니 Enter로 유지, '비밀 키'만 넣으면 됩니다."
open_url "https://supabase.com/dashboard/"
step "프로젝트 'odin_3.0_db' 선택 → 왼쪽 Settings(톱니) → 'API Keys'."
step "'Secret keys' 섹션에서 키를 생성/Reveal 후 복사 (sb_secret_... 형태, 서버 전용·RLS 우회)."
note "옛 UI의 'service_role' 키도 동작하지만 2026년말 폐지 예정 → Secret 키 권장."
ask SUPABASE_URL "Project URL (보통 그대로 Enter):"
SUPABASE_URL=$(_sanitize "$SUPABASE_URL")
write_env SUPABASE_URL "$SUPABASE_URL"
warn "이 비밀 키는 DB 전체 권한을 가집니다 — 절대 공개/커밋 금지(.env에만)."
ask_secret SUPABASE_SERVICE_KEY "Supabase Secret 키(sb_secret_...)를 붙여넣으세요(입력은 가려집니다):"
SUPABASE_SERVICE_KEY=$(_sanitize "$SUPABASE_SERVICE_KEY")
write_env SUPABASE_SERVICE_KEY "$SUPABASE_SERVICE_KEY"

finish
note "다음: data_pipeline 적재 스크립트를 만들어 이 키들로 표를 채웁니다."
